"""furo_id_furo_amplia_varchar

Revision ID: 1195cc9b3863
Revises: fe21179bab23
Create Date: 2026-05-06 11:36:59.730237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1195cc9b3863'
down_revision: Union[str, None] = 'fe21179bab23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('furos', 'id_furo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('furos', 'id_furo',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
