"""add_rdo_entities_and_extend_projeto_furo

Revision ID: 2dd5d8524ef7
Revises: 001
Create Date: 2026-05-05 22:40:18.509081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2dd5d8524ef7'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('sonda', 'percussao', 'trado_mecanico', 'trado_manual', 'cptu', 'mach700', name='tipo_equipamento'), nullable=False),
    sa.Column('status', sa.Enum('operante', 'inoperante', 'manutencao', 'reserva', 'venda', name='status_equipamento'), nullable=False),
    sa.Column('idce_equipamento', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idce_equipamento')
    )
    op.create_index(op.f('ix_equipamentos_id'), 'equipamentos', ['id'], unique=False)
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('guarda_chuva', 'escopo_fechado', name='tipo_contrato'), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_termino', sa.Date(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('gestor_cliente', sa.String(length=200), nullable=True),
    sa.Column('gestor_geothra', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_id'), 'contratos', ['id'], unique=False)
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_termino', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('em_execucao', 'concluido', 'mobilizacao', 'aguardando', name='status_os'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordens_servico_id'), 'ordens_servico', ['id'], unique=False)
    op.create_index(op.f('ix_ordens_servico_projeto_id'), 'ordens_servico', ['projeto_id'], unique=False)
    op.create_table('campanhas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('equipamento_id', sa.Integer(), nullable=True),
    sa.Column('coordenador_geothra_id', sa.Integer(), nullable=True),
    sa.Column('responsavel_medicao_id', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_termino', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('em_execucao', 'concluido', 'mobilizacao', 'aguardando', name='status_os'), nullable=False),
    sa.Column('idce_frenteservico', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coordenador_geothra_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['responsavel_medicao_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idce_frenteservico')
    )
    op.create_index(op.f('ix_campanhas_id'), 'campanhas', ['id'], unique=False)
    op.create_index(op.f('ix_campanhas_os_id'), 'campanhas', ['os_id'], unique=False)
    op.create_table('rdos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campanha_id', sa.Integer(), nullable=False),
    sa.Column('numero_rdo', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo_rdo', sa.String(length=50), nullable=True),
    sa.Column('status_rdo', sa.Enum('rascunho', 'enviado', 'aprovado', 'rejeitado', name='status_rdo'), nullable=False),
    sa.Column('tempo_manha', sa.String(length=50), nullable=True),
    sa.Column('tempo_tarde', sa.String(length=50), nullable=True),
    sa.Column('tempo_noite', sa.String(length=50), nullable=True),
    sa.Column('horimetro_inicial', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('horimetro_final', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tem_hora_extra', sa.Boolean(), nullable=False),
    sa.Column('publicado', sa.Boolean(), nullable=False),
    sa.Column('idce_rdo', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campanha_id'], ['campanhas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idce_rdo')
    )
    op.create_index(op.f('ix_rdos_campanha_id'), 'rdos', ['campanha_id'], unique=False)
    op.create_index(op.f('ix_rdos_id'), 'rdos', ['id'], unique=False)
    op.create_table('rdos_furos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rdo_id', sa.Integer(), nullable=False),
    sa.Column('furo_id', sa.Integer(), nullable=False),
    sa.Column('prof_inicial_dia', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('prof_final_dia', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['furo_id'], ['furos.id'], ),
    sa.ForeignKeyConstraint(['rdo_id'], ['rdos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rdos_furos_furo_id'), 'rdos_furos', ['furo_id'], unique=False)
    op.create_index(op.f('ix_rdos_furos_id'), 'rdos_furos', ['id'], unique=False)
    op.create_index(op.f('ix_rdos_furos_rdo_id'), 'rdos_furos', ['rdo_id'], unique=False)
    op.create_index(op.f('ix_atividades_furo_id'), 'atividades_furo', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.add_column('furos', sa.Column('campanha_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_furos_id'), 'furos', ['id'], unique=False)
    op.create_foreign_key(None, 'furos', 'campanhas', ['campanha_id'], ['id'])
    op.add_column('projetos', sa.Column('contrato_id', sa.Integer(), nullable=True))
    op.add_column('projetos', sa.Column('centro_custo', sa.String(length=30), nullable=True))
    op.add_column('projetos', sa.Column('numero_contrato', sa.String(length=100), nullable=True))
    op.add_column('projetos', sa.Column('objeto_contrato', sa.Text(), nullable=True))
    op.add_column('projetos', sa.Column('gestor_cliente', sa.String(length=200), nullable=True))
    op.add_column('projetos', sa.Column('gestor_geothra', sa.String(length=200), nullable=True))
    op.add_column('projetos', sa.Column('data_inicio', sa.Date(), nullable=True))
    op.add_column('projetos', sa.Column('data_termino', sa.Date(), nullable=True))
    op.add_column('projetos', sa.Column('status_projeto', sa.Enum('em_execucao', 'concluido', 'mobilizacao', 'aguardando', name='status_os'), nullable=False, server_default='em_execucao'))
    op.add_column('projetos', sa.Column('idce_projeto', sa.Integer(), nullable=True))
    op.add_column('projetos', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('projetos', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.drop_constraint('projetos_codigo_key', 'projetos', type_='unique')
    op.create_index(op.f('ix_projetos_codigo'), 'projetos', ['codigo'], unique=True)
    op.create_index(op.f('ix_projetos_id'), 'projetos', ['id'], unique=False)
    op.create_unique_constraint(None, 'projetos', ['idce_projeto'])
    op.create_foreign_key(None, 'projetos', 'contratos', ['contrato_id'], ['id'])
    op.create_index(op.f('ix_sondas_id'), 'sondas', ['id'], unique=False)
    op.drop_constraint('usuarios_email_key', 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_unique_constraint('usuarios_email_key', 'usuarios', ['email'])
    op.drop_index(op.f('ix_sondas_id'), table_name='sondas')
    op.drop_constraint(None, 'projetos', type_='foreignkey')
    op.drop_constraint(None, 'projetos', type_='unique')
    op.drop_index(op.f('ix_projetos_id'), table_name='projetos')
    op.drop_index(op.f('ix_projetos_codigo'), table_name='projetos')
    op.create_unique_constraint('projetos_codigo_key', 'projetos', ['codigo'])
    op.drop_column('projetos', 'longitude')
    op.drop_column('projetos', 'latitude')
    op.drop_column('projetos', 'idce_projeto')
    op.drop_column('projetos', 'status_projeto')
    op.drop_column('projetos', 'data_termino')
    op.drop_column('projetos', 'data_inicio')
    op.drop_column('projetos', 'gestor_geothra')
    op.drop_column('projetos', 'gestor_cliente')
    op.drop_column('projetos', 'objeto_contrato')
    op.drop_column('projetos', 'numero_contrato')
    op.drop_column('projetos', 'centro_custo')
    op.drop_column('projetos', 'contrato_id')
    op.drop_constraint(None, 'furos', type_='foreignkey')
    op.drop_index(op.f('ix_furos_id'), table_name='furos')
    op.drop_column('furos', 'campanha_id')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_atividades_furo_id'), table_name='atividades_furo')
    op.drop_index(op.f('ix_rdos_furos_rdo_id'), table_name='rdos_furos')
    op.drop_index(op.f('ix_rdos_furos_id'), table_name='rdos_furos')
    op.drop_index(op.f('ix_rdos_furos_furo_id'), table_name='rdos_furos')
    op.drop_table('rdos_furos')
    op.drop_index(op.f('ix_rdos_id'), table_name='rdos')
    op.drop_index(op.f('ix_rdos_campanha_id'), table_name='rdos')
    op.drop_table('rdos')
    op.drop_index(op.f('ix_campanhas_os_id'), table_name='campanhas')
    op.drop_index(op.f('ix_campanhas_id'), table_name='campanhas')
    op.drop_table('campanhas')
    op.drop_index(op.f('ix_ordens_servico_projeto_id'), table_name='ordens_servico')
    op.drop_index(op.f('ix_ordens_servico_id'), table_name='ordens_servico')
    op.drop_table('ordens_servico')
    op.drop_index(op.f('ix_contratos_id'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_equipamentos_id'), table_name='equipamentos')
    op.drop_table('equipamentos')
    # ### end Alembic commands ###
