"""cliente_recebe_idce_e_logotipo

Revision ID: b49a0c359247
Revises: d75bb7bab2a9
Create Date: 2026-05-05 23:10:13.495992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b49a0c359247'
down_revision: Union[str, None] = 'd75bb7bab2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('idce_cliente', sa.Integer(), nullable=True))
    op.add_column('clientes', sa.Column('logotipo_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_clientes_idce_cliente'), 'clientes', ['idce_cliente'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientes_idce_cliente'), table_name='clientes')
    op.drop_column('clientes', 'logotipo_url')
    op.drop_column('clientes', 'idce_cliente')
    # ### end Alembic commands ###
