"""projeto_ajusta_campos_para_rdo

Revision ID: b743820175f1
Revises: 28435fe4945a
Create Date: 2026-05-05 23:26:15.638235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b743820175f1'
down_revision: Union[str, None] = '28435fe4945a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos', sa.Column('local_execucao', sa.String(length=255), nullable=True))
    op.alter_column('projetos', 'sonda_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projetos', 'uf',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.drop_column('projetos', 'cidade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projetos', sa.Column('cidade', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('projetos', 'uf',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('projetos', 'sonda_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('projetos', 'local_execucao')
    # ### end Alembic commands ###
