"""campanha_vincula_direto_obra

Revision ID: d75bb7bab2a9
Revises: 2dd5d8524ef7
Create Date: 2026-05-05 23:06:00.726192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd75bb7bab2a9'
down_revision: Union[str, None] = '2dd5d8524ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campanhas', sa.Column('obra_id', sa.Integer(), nullable=True))
    op.alter_column('campanhas', 'os_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_campanhas_obra_id'), 'campanhas', ['obra_id'], unique=False)
    op.create_foreign_key(None, 'campanhas', 'projetos', ['obra_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campanhas', type_='foreignkey')
    op.drop_index(op.f('ix_campanhas_obra_id'), table_name='campanhas')
    op.alter_column('campanhas', 'os_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('campanhas', 'obra_id')
    # ### end Alembic commands ###
