"""furo_e_rdofuro_recebem_idce

Revision ID: fe21179bab23
Revises: b743820175f1
Create Date: 2026-05-06 11:27:54.162490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fe21179bab23'
down_revision: Union[str, None] = 'b743820175f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('furos', sa.Column('idce_furo', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_furos_idce_furo'), 'furos', ['idce_furo'], unique=True)
    op.add_column('rdos_furos', sa.Column('idce_rdofuro', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rdos_furos_idce_rdofuro'), 'rdos_furos', ['idce_rdofuro'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rdos_furos_idce_rdofuro'), table_name='rdos_furos')
    op.drop_column('rdos_furos', 'idce_rdofuro')
    op.drop_index(op.f('ix_furos_idce_furo'), table_name='furos')
    op.drop_column('furos', 'idce_furo')
    # ### end Alembic commands ###
